spring:
  datasource:
    username: root
    password: jt123456
    url: jdbc:mysql://localhost:3306/db1
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
